
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mealplanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - mealplanner-data:/var/lib/postgresql/data

volumes:
  mealplanner-data:
