version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: mealplanner-redis
    ports:
      - "6379:6379"            # ← host 6379 → container 6379
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  postgres:
    image: postgres:15
    ports:
      - "15433:5432"
    environment:
      POSTGRES_DB: mealplanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mealplanner-data:/var/lib/postgresql/data

volumes:
  mealplanner-data:
